import {
  websiteDomainCreateSchema,
  websiteDomainListSchema,
  websiteDomainResponseSchema,
  websiteEmbedBodySchema,
  websiteEmbedListSchema,
  websiteEmbedResponseSchema,
  websiteMenuBodySchema,
  websiteMenuListSchema,
  websiteMenuResponseSchema,
  websiteNewsBodySchema,
  websiteNewsListSchema,
  websiteNewsSaveResponseSchema,
  websitePageBodySchema,
  websitePageListSchema,
  websitePublicEmbedSchema,
  websitePublicPageSchema,
  websitePublicNewsSchema,
  websiteSaveResponseSchema,
  websiteSettingsBodySchema,
  websiteSettingsResponseSchema,
} from '@shared/schemas/website';
import { z } from 'zod';

import type { ServerModule } from '../../lib/module-contract';

import { createWebsiteRouter } from './routes';
import { publicPlansSchema } from './schema';

const routes = [
  {
    method: 'get',
    path: '/api/v1/website/public/plans',
    summary: 'List active public organization subscription plans',
    response: publicPlansSchema,
    public: true,
  },
  {
    method: 'get',
    path: '/api/v1/website/public/{orgSlug}/news',
    summary: 'List published public organization news posts',
    response: websitePublicNewsSchema,
    public: true,
  },
  {
    method: 'get',
    path: '/api/v1/website/public/{orgSlug}/pages/{pageSlug}',
    summary: 'Get a published public organization website page',
    response: websitePublicPageSchema,
    public: true,
  },
  {
    method: 'get',
    path: '/api/v1/website/public/{orgSlug}/embeds/{publicKey}',
    summary:
      'Get public program, schedule, standings, or registration widget data',
    response: websitePublicEmbedSchema,
    public: true,
  },
  {
    method: 'get',
    path: '/api/v1/website/public/{orgSlug}/sitemap.xml',
    summary: 'Get the public organization website sitemap',
    response: z.string(),
    contentType: 'application/xml',
    public: true,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/news',
    summary: 'List organization website news posts',
    response: websiteNewsListSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/news',
    summary: 'Create an organization website news post',
    body: websiteNewsBodySchema,
    response: websiteNewsSaveResponseSchema,
    status: 201,
  },
  {
    method: 'put',
    path: '/api/v1/website/orgs/{orgId}/news/{postId}',
    summary: 'Update a website news post with optimistic version checking',
    body: websiteNewsBodySchema,
    response: websiteNewsSaveResponseSchema,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/settings',
    summary: 'Get organization website settings',
    response: websiteSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/domains',
    summary: 'List organization website domains',
    response: websiteDomainListSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/domains',
    summary: 'Add a custom website domain and issue an ownership token',
    body: websiteDomainCreateSchema,
    response: websiteDomainResponseSchema,
    status: 201,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/domains/{domainId}/verify',
    summary: 'Verify custom domain ownership and active TLS certificate',
    body: z.strictObject({}),
    response: websiteDomainResponseSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/domains/{domainId}/primary',
    summary: 'Set a fully verified website domain as primary',
    body: z.strictObject({}),
    response: websiteDomainResponseSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/domains/{domainId}/disable',
    summary: 'Disable a website domain while retaining its audit record',
    body: z.strictObject({}),
    response: websiteDomainResponseSchema,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/embeds',
    summary: 'List organization public website widgets',
    response: websiteEmbedListSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/embeds',
    summary: 'Create a public website widget',
    body: websiteEmbedBodySchema,
    response: websiteEmbedResponseSchema,
    status: 201,
  },
  {
    method: 'put',
    path: '/api/v1/website/orgs/{orgId}/embeds/{embedId}',
    summary: 'Update a website widget with optimistic version checking',
    body: websiteEmbedBodySchema,
    response: websiteEmbedResponseSchema,
  },
  {
    method: 'put',
    path: '/api/v1/website/orgs/{orgId}/settings',
    summary:
      'Update organization website settings with optimistic version checking',
    body: websiteSettingsBodySchema,
    response: websiteSettingsResponseSchema,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/menus',
    summary: 'List organization website navigation menus',
    response: websiteMenuListSchema,
  },
  {
    method: 'put',
    path: '/api/v1/website/orgs/{orgId}/menus',
    summary: 'Update an organization website navigation menu',
    body: websiteMenuBodySchema,
    response: websiteMenuResponseSchema,
  },
  {
    method: 'get',
    path: '/api/v1/website/orgs/{orgId}/pages',
    summary: 'List website pages for an organization editor',
    response: websitePageListSchema,
  },
  {
    method: 'post',
    path: '/api/v1/website/orgs/{orgId}/pages',
    summary: 'Create an organization website page',
    body: websitePageBodySchema,
    response: websiteSaveResponseSchema,
    status: 201,
  },
  {
    method: 'put',
    path: '/api/v1/website/orgs/{orgId}/pages/{pageId}',
    summary: 'Update a website page with optimistic version checking',
    body: websitePageBodySchema,
    response: websiteSaveResponseSchema,
  },
] as const;

export const moduleDefinition = {
  name: 'website',
  path: '/api/v1/website',
  router: createWebsiteRouter,
  openapiRoutes: routes,
} satisfies ServerModule & { openapiRoutes: readonly unknown[] };
