-- Keep parent deletes and referenced-key updates efficient for Phase 11 records.
CREATE INDEX volunteer_signups_person_fk_idx ON volunteer_signups(org_id, person_id);
CREATE INDEX volunteer_signups_created_by_fk_idx ON volunteer_signups(created_by);
CREATE INDEX volunteer_signups_credited_by_fk_idx ON volunteer_signups(credited_by);
CREATE INDEX volunteer_buyouts_created_by_fk_idx ON volunteer_buyouts(created_by);
CREATE INDEX volunteer_buyouts_household_fk_idx ON volunteer_buyouts(org_id, household_id);
CREATE INDEX volunteer_buyouts_person_fk_idx ON volunteer_buyouts(org_id, person_id);
CREATE INDEX volunteer_buyouts_invoice_fk_idx ON volunteer_buyouts(org_id, invoice_id);
CREATE INDEX volunteer_roles_created_by_fk_idx ON volunteer_roles(created_by);
CREATE INDEX volunteer_requirements_created_by_fk_idx ON volunteer_requirements(created_by);
CREATE INDEX volunteer_requirements_program_fk_idx ON volunteer_requirements(org_id, program_id);
CREATE INDEX volunteer_requirements_buyout_offering_fk_idx ON volunteer_requirements(org_id, buyout_offering_id);
CREATE INDEX volunteer_shifts_created_by_fk_idx ON volunteer_shifts(created_by);
CREATE INDEX volunteer_shifts_event_fk_idx ON volunteer_shifts(org_id, event_id);
CREATE INDEX volunteer_shifts_facility_fk_idx ON volunteer_shifts(org_id, facility_id);
CREATE INDEX team_ledgers_created_by_fk_idx ON team_ledgers(created_by);
CREATE INDEX team_ledger_entries_created_by_fk_idx ON team_ledger_entries(created_by);
CREATE INDEX team_ledger_entries_approved_by_fk_idx ON team_ledger_entries(approved_by);
CREATE INDEX team_ledger_entries_receipt_file_fk_idx ON team_ledger_entries(org_id, receipt_file_id);
CREATE INDEX team_ledger_entries_payment_fk_idx ON team_ledger_entries(org_id, payment_id);
CREATE INDEX team_ledger_entries_invoice_fk_idx ON team_ledger_entries(org_id, invoice_id);
CREATE INDEX team_ledger_entries_invoice_line_fk_idx ON team_ledger_entries(org_id, invoice_line_id);
CREATE INDEX team_fee_assessments_created_by_fk_idx ON team_fee_assessments(created_by);
CREATE INDEX team_fee_assessments_installment_template_fk_idx ON team_fee_assessments(org_id, installment_template_id);
CREATE INDEX team_fee_obligations_account_fk_idx ON team_fee_obligations(account_id);
CREATE INDEX team_fee_obligations_team_ledger_fk_idx ON team_fee_obligations(org_id, team_ledger_id);
CREATE INDEX team_fee_obligations_person_fk_idx ON team_fee_obligations(org_id, person_id);
CREATE INDEX team_fee_obligations_invoice_line_fk_idx ON team_fee_obligations(org_id, invoice_line_id);
CREATE INDEX fundraising_settings_updated_by_fk_idx ON fundraising_settings(updated_by);
CREATE INDEX reimbursement_requests_requester_account_fk_idx ON reimbursement_requests(requester_account_id);
CREATE INDEX reimbursement_requests_decided_by_fk_idx ON reimbursement_requests(decided_by);
CREATE INDEX reimbursement_requests_person_fk_idx ON reimbursement_requests(org_id, requester_person_id);
CREATE INDEX reimbursement_requests_receipt_file_fk_idx ON reimbursement_requests(org_id, receipt_file_id);
CREATE INDEX reimbursement_requests_ledger_entry_fk_idx ON reimbursement_requests(org_id, ledger_entry_id);
CREATE INDEX sponsors_created_by_fk_idx ON sponsors(created_by);
CREATE INDEX sponsors_logo_file_fk_idx ON sponsors(org_id, logo_file_id);
CREATE INDEX sponsors_invoice_fk_idx ON sponsors(org_id, invoice_id);
CREATE INDEX fundraising_campaigns_created_by_fk_idx ON fundraising_campaigns(created_by);
CREATE INDEX fundraising_campaigns_team_season_fk_idx ON fundraising_campaigns(org_id, team_season_id);
CREATE INDEX fundraising_campaigns_image_file_fk_idx ON fundraising_campaigns(org_id, image_file_id);
CREATE INDEX donations_donor_account_fk_idx ON donations(donor_account_id);
CREATE INDEX donations_invoice_fk_idx ON donations(org_id, invoice_id);
CREATE INDEX donations_invoice_line_fk_idx ON donations(org_id, invoice_line_id);
CREATE INDEX donations_payment_fk_idx ON donations(org_id, payment_id);
CREATE INDEX products_created_by_fk_idx ON products(created_by);
CREATE INDEX products_category_fk_idx ON products(org_id, category_id);
CREATE INDEX inventory_movements_created_by_fk_idx ON inventory_movements(created_by);
CREATE INDEX store_orders_invoice_fk_idx ON store_orders(org_id, invoice_id);
CREATE INDEX store_orders_account_fk_idx ON store_orders(account_id);
CREATE INDEX store_orders_household_fk_idx ON store_orders(org_id, household_id);
CREATE INDEX store_orders_registration_fk_idx ON store_orders(org_id, registration_id);
CREATE INDEX store_orders_team_season_fk_idx ON store_orders(org_id, team_season_id);
CREATE INDEX store_order_lines_product_fk_idx ON store_order_lines(org_id, product_id);
CREATE INDEX store_order_lines_product_variant_fk_idx ON store_order_lines(org_id, product_variant_id);
CREATE INDEX store_order_lines_registration_fk_idx ON store_order_lines(org_id, registration_id);
CREATE INDEX store_order_lines_person_fk_idx ON store_order_lines(org_id, person_id);
CREATE INDEX store_order_lines_team_season_fk_idx ON store_order_lines(org_id, team_season_id);
CREATE INDEX store_fulfillments_fulfilled_by_fk_idx ON store_fulfillments(fulfilled_by);
CREATE INDEX store_registration_addons_product_fk_idx ON store_registration_addons(org_id, product_id);
