/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountConsents {
  accepted_at: Generated<Timestamp>;
  account_id: string;
  document_text: string;
  document_version: string;
  id: string;
  ip: string | null;
  kind: string;
  user_agent: string | null;
}

export interface Accounts {
  created_at: Generated<Timestamp>;
  date_of_birth: Timestamp;
  email: string;
  email_verified_at: Timestamp | null;
  first_name: string;
  id: string;
  last_name: string;
  last_sign_in_at: Timestamp | null;
  locale: Generated<string>;
  password_hash: string | null;
  phone_e164: string | null;
  phone_verified_at: Timestamp | null;
  status: Generated<string>;
  timezone: string | null;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AuditLog {
  action: string;
  actor_account_id: string | null;
  changes: Generated<Json>;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  id: string;
  impersonation_id: string | null;
  ip: string | null;
  org_id: string | null;
  request_id: string | null;
  user_agent: string | null;
}

export interface AuthTokens {
  account_id: string | null;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  email: string;
  expires_at: Timestamp;
  id: string;
  org_id: string | null;
  payload: Generated<Json>;
  purpose: string;
  revoked_at: Timestamp | null;
  subject_key: Generated<string>;
  token_hash: Buffer;
}

export interface DeviceTokens {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  last_seen_at: Generated<Timestamp>;
  platform: string;
  revoked_at: Timestamp | null;
  token_or_subscription: Json;
  updated_at: Generated<Timestamp>;
}

export interface IdempotencyKeys {
  actor_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  org_id: string;
  request_hash: Buffer;
  response_body: Json | null;
  response_status: number | null;
  updated_at: Generated<Timestamp>;
}

export interface MfaFactors {
  account_id: string;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  last_used_step: number | null;
  secret_enc: Buffer;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface MfaRecoveryCodes {
  account_id: string;
  code_hash: Buffer;
  created_at: Generated<Timestamp>;
  id: string;
  used_at: Timestamp | null;
}

export interface Organizations {
  address: Json | null;
  application_fee_bps: Generated<number>;
  application_fee_fixed_cents: Generated<number>;
  brand: Generated<Json>;
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  default_locale: Generated<string>;
  ein_enc: Buffer | null;
  email: string | null;
  id: string;
  kind: string;
  legal_name: string | null;
  logo_file_id: string | null;
  name: string;
  nonprofit: Generated<boolean>;
  phone: string | null;
  plan_id: string | null;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  timezone: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  website_url: string | null;
}

export interface OrgCounters {
  created_at: Generated<Timestamp>;
  name: string;
  next_value: Generated<number>;
  org_id: string;
  updated_at: Generated<Timestamp>;
}

export interface OrgMemberships {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  invited_by: string | null;
  joined_at: Timestamp | null;
  org_id: string;
  status: string;
  title: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Plans {
  active: Generated<boolean>;
  application_fee_bps: number;
  application_fee_fixed_cents: number;
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  limits: Generated<Json>;
  monthly_price_cents: number;
  name: string;
  stripe_price_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface RoleAssignments {
  account_id: string;
  created_at: Generated<Timestamp>;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: string;
  org_id: string;
  pending_mfa: Generated<boolean>;
  revoked_at: Timestamp | null;
  role: string;
  scope_id: string | null;
  scope_type: string;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  name: string;
  version: number;
}

export interface SecurityEvents {
  account_id: string | null;
  action: string;
  created_at: Generated<Timestamp>;
  details: Generated<Json>;
  id: string;
  ip: string | null;
  user_agent: string | null;
}

export interface Sessions {
  absolute_expires_at: Timestamp;
  account_id: string;
  client: string;
  created_at: Generated<Timestamp>;
  elevated_until: Timestamp | null;
  id: string;
  idle_expires_at: Timestamp;
  impersonation_id: string | null;
  ip: string | null;
  kind: string;
  mfa_verified_at: Timestamp | null;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
}

export interface DB {
  account_consents: AccountConsents;
  accounts: Accounts;
  audit_log: AuditLog;
  auth_tokens: AuthTokens;
  device_tokens: DeviceTokens;
  idempotency_keys: IdempotencyKeys;
  mfa_factors: MfaFactors;
  mfa_recovery_codes: MfaRecoveryCodes;
  org_counters: OrgCounters;
  org_memberships: OrgMemberships;
  organizations: Organizations;
  plans: Plans;
  role_assignments: RoleAssignments;
  schema_migrations: SchemaMigrations;
  security_events: SecurityEvents;
  sessions: Sessions;
}
