/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLog {
  action: string;
  actor_account_id: string | null;
  changes: Generated<Json>;
  created_at: Generated<Timestamp>;
  entity_id: string | null;
  entity_type: string;
  id: string;
  impersonation_id: string | null;
  ip: string | null;
  org_id: string | null;
  request_id: string | null;
  user_agent: string | null;
}

export interface IdempotencyKeys {
  actor_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  org_id: string;
  request_hash: Buffer;
  response_body: Json | null;
  response_status: number | null;
  updated_at: Generated<Timestamp>;
}

export interface Organizations {
  address: Json | null;
  application_fee_bps: Generated<number>;
  application_fee_fixed_cents: Generated<number>;
  brand: Generated<Json>;
  country: Generated<string>;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  default_locale: Generated<string>;
  ein_enc: Buffer | null;
  email: string | null;
  id: string;
  kind: string;
  legal_name: string | null;
  logo_file_id: string | null;
  name: string;
  nonprofit: Generated<boolean>;
  phone: string | null;
  plan_id: string | null;
  settings: Generated<Json>;
  slug: string;
  status: Generated<string>;
  timezone: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
  website_url: string | null;
}

export interface OrgCounters {
  created_at: Generated<Timestamp>;
  name: string;
  next_value: Generated<number>;
  org_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Plans {
  active: Generated<boolean>;
  application_fee_bps: number;
  application_fee_fixed_cents: number;
  created_at: Generated<Timestamp>;
  id: string;
  key: string;
  limits: Generated<Json>;
  monthly_price_cents: number;
  name: string;
  stripe_price_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  name: string;
  version: number;
}

export interface DB {
  audit_log: AuditLog;
  idempotency_keys: IdempotencyKeys;
  org_counters: OrgCounters;
  organizations: Organizations;
  plans: Plans;
  schema_migrations: SchemaMigrations;
}
