import type { InvoicePlan } from "./invoice-installments";
export type Program = {
  id: string;
  name: string;
  type: string;
  sport: string;
  gender: string;
  level: string;
  season: string;
  status: string;
  grouped: boolean | number;
  parent_id: string | null;
  start_date: string;
  end_date: string;
  registration_start: string;
  registration_end: string;
  fee_cents: number;
  capacity: number | null;
  waitlist: boolean | number;
  public: boolean | number;
  description: string;
  audience: string;
  location_id: string;
  start_visible: boolean;
  end_visible: boolean;
  start_tentative: boolean;
  days: string[];
  start_time: string;
  end_time: string;
  sponsor: string;
  host: string;
  format: string;
  registration_status: string;
  registration_password: string;
  code: string;
  integration_codes: string[];
  accounting_codes?: string[];
  paid: number;
  invoiced: number;
  paid_invoices: number;
  partial_invoices: number;
  unpaid_invoices: number;
  overdue: number;
  outstanding: number;
  players: number;
  free_agents: number;
  staff: number;
  teams: number;
  registrations: number;
};
export type Person = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  birthdate: string;
  kind: string;
  household_id: string | null;
  household_name?: string;
  household_role?: string;
  created_at: string;
  last_login?: string;
  phone?: string;
  secondary_email?: string;
  address?: string;
  city?: string;
  state?: string;
  postal_code?: string;
  biography?: string;
  notes?: string;
  marketing_opt_in?: boolean;
  sms_opt_in?: boolean;
  email_status?: string;
  archived_at?: string | null;
};
export type Team = {
  id: string;
  program_id: string;
  name: string;
  division: string;
  players: number;
  created_at: string;
  locked: number;
};
export type Location = {
  id: string;
  name: string;
  address: string;
  parent_id: string | null;
  address2?: string;
  city?: string;
  state?: string;
  postal_code?: string;
  description?: string;
};
export type Household = {
  id: string;
  name: string;
  type?: string;
  description?: string;
  members: Person[];
  registrations: MemberRegistration[];
};
export type MemberRegistration = Registration & {
  program_name: string;
  program_status: string;
  season: string;
  team_name: string;
  invoice_number: number;
  end_date: string;
};
export type Credit = {
  id: string;
  person_id: string;
  first_name: string;
  last_name: string;
  amount_cents: number;
  balance_cents: number;
  description: string;
  expires: string;
  created_at: string;
};
export type Discount = {
  id: string;
  program_id: string | null;
  name: string;
  description: string;
  code: string;
  kind: "Fixed" | "Percentage";
  value: number;
  expires: string;
  redemption_limit: number | null;
  multi_use: number | boolean;
  active: number | boolean;
  created_at: string;
  redeemed: number;
};
export type Registration = {
  original_role?: string | null;
  team_name?: string | null;
  id: string;
  program_id: string;
  person_id: string;
  team_id: string | null;
  first_name: string;
  last_name: string;
  email: string;
  gender: string;
  birthdate: string;
  role: string;
  status: string;
  waiver_accepted_at: string | null;
  invoice_id: string | null;
  paid_cents: number;
  total_cents: number;
  created_at: string;
};
export type Invoice = {
  payment_plan?: InvoicePlan | null;
  id: string;
  number: number;
  program_id: string;
  first_name: string;
  last_name: string;
  description: string;
  total_cents: number;
  paid_cents: number;
  due_date: string;
  created_at: string;
  voided: number;
  order_id?: string;
  subtotal_cents?: number;
  shipping_cents?: number;
  tax_cents?: number;
  credit_applications?: {
    id: string;
    amount_cents: number;
    created_at: string;
    description: string;
  }[];
  base_cents?: number;
  discount_cents?: number;
  discount_code?: string;
  person: Person;
  transactions: {
    id: string;
    amount_cents: number;
    method: string;
    created_at: string;
  }[];
};
export type Activity = {
  activity_type?: string;
  description?: string;
  location_note?: string;
  id: string;
  program_id: string;
  type: string;
  title: string;
  home_team_id: string | null;
  away_team_id: string | null;
  location_id: string | null;
  start_at: string;
  end_at: string;
  state: string;
  home_score: number | null;
  away_score: number | null;
  published: number;
  notes: string;
  game_type?: string;
  overtime?: boolean;
  forfeit?: string;
  exclude_home?: boolean;
  exclude_away?: boolean;
  match_scores?: { home: number; away: number }[];
};
