import {
  contestResultBodySchema,
  contributionBodySchema,
  createRelationshipBodySchema,
  feeAssessmentBodySchema,
  federationDisciplineBodySchema,
  federationDisciplineUpdateSchema,
  memberPayerBodySchema,
  refereeAssignmentBodySchema,
  refereeBodySchema,
  rosterWindowBodySchema,
  scheduleRunBodySchema,
  sharingProposalBodySchema,
  submitEntryBodySchema,
  reviewEntryBodySchema,
  assignmentUpdateSchema,
} from '@shared/schemas/federation';
import { z } from 'zod';

import type { ServerModule } from '../../lib/module-contract';

import { createFederationRouter } from './routes';

const base = '/api/v1/federation/organizations/{orgId}';
const json = z.json();
const versionBody = z.strictObject({ version: z.number().int().positive() });

export const moduleDefinition = {
  name: 'federation',
  path: '/api/v1/federation',
  router: createFederationRouter,
  jobs: [],
  permissions: [],
  notificationTypes: [],
  errorCodes: [
    'FEDERATION_CONFLICT',
    'FEDERATION_RULE',
    'FEDERATION_SHARING_DENIED',
    'FEDERATION_UNAVAILABLE',
  ],
  openapiRoutes: [
    {
      method: 'get',
      path: `${base}/relationships`,
      summary: 'List federation relationships for this organization',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/relationships/lookup`,
      summary: 'Search organizations to invite or request membership',
      query: { q: z.string().min(2).max(100) },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships`,
      summary: 'Invite a member club or request to join a federation',
      body: createRelationshipBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/relationships/{relationshipId}`,
      summary: 'Get a federation relationship',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/accept`,
      summary: 'Accept a federation invitation or join request',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/decline`,
      summary: 'Decline a federation invitation or join request',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/suspend`,
      summary: 'Suspend an active federation relationship',
      body: z.strictObject({
        reason: z.string().trim().max(2000).optional(),
        version: z.number().int().positive(),
      }),
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/resume`,
      summary: 'Resume a suspended federation relationship',
      body: versionBody,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/end`,
      summary: 'End a federation relationship',
      body: z.strictObject({
        reason: z.string().trim().max(2000).optional(),
        version: z.number().int().positive(),
      }),
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/sharing`,
      summary: 'Propose a data-sharing change (requires other-side acceptance)',
      body: sharingProposalBodySchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/sharing/accept`,
      summary: 'Accept a pending data-sharing proposal',
      body: versionBody,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/relationships/{relationshipId}/sharing/decline`,
      summary: 'Decline a pending data-sharing proposal',
      body: versionBody,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/programs`,
      summary: 'List this organization’s programs and divisions',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/league-programs`,
      summary:
        'Read a league’s programs for entry submission (requires teamEntries sharing)',
      query: { leagueOrgId: z.uuid() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/my-teams`,
      summary: 'List this organization’s team seasons for entry submission',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/my-spaces`,
      summary: 'List this organization’s spaces for availability offers',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/members`,
      summary: 'List member clubs with entry, discipline, and fee rollups',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/members/{memberOrgId}/teams`,
      summary: 'Read member club teams (requires teamEntries sharing)',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/members/{memberOrgId}/roster`,
      summary: 'Read a member team roster (requires rosters sharing)',
      query: { teamSeasonId: z.uuid() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/members/{memberOrgId}/compliance`,
      summary:
        'Read member staff compliance rollup (requires complianceStatus sharing)',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/members/{memberOrgId}/discipline`,
      summary:
        'Read member-club discipline records (requires discipline sharing)',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/entries`,
      summary: 'List federation team entries in league programs',
      query: { programId: z.uuid().optional() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/entries/{entryId}`,
      summary: 'Get a federation entry with its roster snapshot',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/entries/{entryId}/review`,
      summary: 'Accept, waitlist, or decline a federation entry',
      body: reviewEntryBodySchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/submitted-entries`,
      summary: "List this club's submitted federation entries",
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/submitted-entries`,
      summary: 'Submit a club team into a league program with roster snapshot',
      body: submitEntryBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/submitted-entries/{entryId}/withdraw`,
      summary: 'Withdraw a submitted federation entry',
      body: z.strictObject({ leagueOrgId: z.uuid() }),
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/submitted-entries/{entryId}/roster`,
      summary: 'Resubmit the roster snapshot before the league freeze',
      body: z.strictObject({ leagueOrgId: z.uuid() }),
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'put',
      path: `${base}/programs/{programId}/roster-window`,
      summary: 'Set the roster submission window for a league program',
      body: rosterWindowBodySchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/programs/{programId}/roster-freeze`,
      summary: 'Freeze all live roster snapshots for a program',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/space-contributions`,
      summary: 'Offer member-club field windows to the league schedule pool',
      body: contributionBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/space-contributions`,
      summary: "List this club's contributed windows",
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/space-contributions/{contributionId}/withdraw`,
      summary: 'Withdraw an unused contributed window',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/programs/{programId}/availability`,
      summary:
        'Aggregate league + member-club availability for schedule generation',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/schedule-runs`,
      summary: 'Generate a draft league schedule over combined availability',
      body: scheduleRunBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/schedule-runs`,
      summary: 'List league schedule generation runs',
      query: { programId: z.uuid().optional() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/schedule-runs/{runId}`,
      summary: 'Get a schedule run with its draft events',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/schedule-runs/{runId}/apply`,
      summary: 'Apply a draft schedule (creates events, contests, host bookings)',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/schedule-runs/{runId}/publish`,
      summary: 'Publish applied league schedule events',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/schedule-runs/{runId}/discard`,
      summary: 'Discard a draft schedule run',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/hosted-games`,
      summary: 'List league games hosted on this club’s spaces',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/programs/{programId}/contests`,
      summary: 'List league contests with participants and results',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/contests/{contestId}/result`,
      summary: 'Enter a result on a league contest',
      body: contestResultBodySchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/hosted-games/{linkId}/result`,
      summary: 'Enter a result as the hosting member club',
      body: contestResultBodySchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/programs/{programId}/standings`,
      summary: 'League standings across member-club teams',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/member-standings`,
      summary: 'Member-club view of league standings',
      query: { leagueOrgId: z.uuid(), programId: z.uuid() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/federation-discipline`,
      summary: 'List league-issued federation discipline records',
      query: { memberOrgId: z.uuid().optional() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/federation-discipline`,
      summary: 'Issue discipline against a member-club subject',
      body: federationDisciplineBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'patch',
      path: `${base}/federation-discipline/{recordId}`,
      summary: 'Serve, appeal, or overturn a federation discipline record',
      body: federationDisciplineUpdateSchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/member-discipline`,
      summary: 'Member club reads league discipline records about itself',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/referees`,
      summary: 'List the league referee pool',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/referees`,
      summary: 'Add a person to the league referee pool',
      body: refereeBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/referees/{profileId}/remove`,
      summary: 'Remove a referee from the pool',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/referee-assignments`,
      summary: 'List referee assignments',
      query: { contestId: z.uuid().optional() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/contests/{contestId}/assignments`,
      summary: 'Assign a pool referee to a league contest',
      body: refereeAssignmentBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'patch',
      path: `${base}/referee-assignments/{assignmentId}`,
      summary: 'Transition a referee assignment',
      body: assignmentUpdateSchema,
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/member-payers`,
      summary: 'List member-club billing contacts (league view)',
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/member-payers`,
      summary: 'Member club sets its league billing contact',
      body: memberPayerBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/fees`,
      summary: 'List league fee assessments',
      query: { memberOrgId: z.uuid().optional() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/fees`,
      summary: 'Draft a fee assessment against a member club',
      body: feeAssessmentBodySchema,
      response: json,
      status: 201,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/fees/{assessmentId}/issue`,
      summary: 'Issue the finance invoice for a fee assessment',
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'post',
      path: `${base}/fees/{assessmentId}/void`,
      summary: 'Void a fee assessment',
      body: z.strictObject({
        action: z.literal('void'),
        reason: z.string().trim().max(1000).optional(),
      }),
      response: json,
      idempotencyKey: true,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/club-fees`,
      summary: 'Member club reads its league fee assessments',
      query: { leagueOrgId: z.uuid() },
      response: json,
      tags: ['federation'],
    },
    {
      method: 'get',
      path: `${base}/dashboard`,
      summary: 'Association dashboard rollup',
      response: json,
      tags: ['federation'],
    },
  ],
} satisfies ServerModule & { openapiRoutes: readonly unknown[] };
