import { type AgeGroupConfig } from '../age.js';
import { type StatDefinition } from '../schema.js';

import {
  bout,
  judged,
  measured,
  placement,
  score,
  sets,
  t,
  timed,
  type TemplateSeed,
} from './base.js';

const birth: AgeGroupConfig = {
  method: 'birth_year',
  label: 'U{n}',
  seasonYearBasis: 'season_end',
};
const birthN: AgeGroupConfig = {
  method: 'birth_year',
  label: '{n}U',
  seasonYearBasis: 'season_end',
};
const age: AgeGroupConfig = {
  method: 'age_on_date',
  monthDay: '08-01',
  yearBasis: 'season_start',
};
const grade: AgeGroupConfig = {
  method: 'school_grade',
  schoolYearCutoff: '08-01',
};
const none: AgeGroupConfig = { method: 'none' };
const stats = (
  key: string,
  label: string,
  abbreviation: string,
): StatDefinition => ({
  key,
  label: t(label),
  abbreviation,
  level: 'athlete',
  valueType: 'integer',
  aggregate: 'sum',
  public: false,
});
const methods = [
  ['fall', 6],
  ['tech_fall', 5],
  ['major_decision', 4],
  ['decision', 3],
  ['forfeit', 6],
] as const;

export const templateSeeds: Record<string, TemplateSeed> = {
  soccer: {
    key: 'soccer',
    name: 'Soccer',
    es: 'Fútbol',
    category: 'team',
    formats: [score('Half', 2, true)],
    positions: 'GK|DEF|MID|FWD',
    rosterMax: 18,
    onField: 11,
    age: birth,
    venue: 'field',
    contest: 'Game',
    duration: 90,
    rubric: 'First touch|Passing|Dribbling|Defending|Game IQ|Athleticism',
    officials: 'Referee|Assistant referee',
    discipline: 'Yellow card|Red card',
    minimumPlayRule: { unit: 'minutes', defaultRequirement: 30 },
  },
  futsal: {
    key: 'futsal',
    name: 'Futsal',
    category: 'team',
    formats: [score('Half', 2, true)],
    positions: 'GK|Field',
    rosterMax: 14,
    onField: 5,
    age: birth,
    venue: 'court',
    contest: 'Match',
    duration: 40,
    rubric: 'Ball control|Passing|Movement|Defending',
    officials: 'Referee|Second referee',
    discipline: 'Yellow card|Red card',
    stats: [stats('accumulated_fouls', 'Accumulated fouls', 'AF')],
  },
  basketball: {
    key: 'basketball',
    name: 'Basketball',
    es: 'Baloncesto',
    category: 'team',
    formats: [
      score('Quarter', 4, false, {
        overtime: { label: t('Overtime', 'Prórroga') },
      }),
    ],
    positions: 'PG|SG|SF|PF|C',
    rosterMax: 12,
    onField: 5,
    age: grade,
    venue: 'court',
    contest: 'Game',
    rubric: 'Ball handling|Shooting|Passing|Defense|Court awareness',
    officials: 'Referee|Umpire',
    discipline: 'Technical foul|Ejection',
    stats: [stats('fouls', 'Fouls', 'F')],
  },
  baseball: {
    key: 'baseball',
    name: 'Baseball',
    es: 'Béisbol',
    category: 'team',
    formats: [
      score('Inning', 6, false, { mercyRule: { margin: 10, afterPeriod: 4 } }),
    ],
    positions: 'P|C|1B|2B|3B|SS|LF|CF|RF|DH',
    rosterMax: 14,
    onField: 9,
    age,
    venue: 'field',
    contest: 'Game',
    duration: 120,
    rubric: 'Hitting|Fielding|Throwing|Baserunning|Game awareness',
    officials: 'Plate umpire|Base umpire',
    discipline: 'Ejection',
    stats: [stats('pitch_count', 'Pitch count', 'PC')],
  },
  softball: {
    key: 'softball',
    name: 'Softball',
    category: 'team',
    formats: [
      score('Inning', 7, false, { mercyRule: { margin: 10, afterPeriod: 5 } }),
    ],
    positions: 'P|C|1B|2B|3B|SS|LF|CF|RF|DP|FLEX',
    rosterMax: 15,
    onField: 9,
    age,
    venue: 'field',
    contest: 'Game',
    duration: 120,
    rubric: 'Hitting|Fielding|Throwing|Baserunning|Game awareness',
    officials: 'Plate umpire|Base umpire',
    discipline: 'Ejection',
  },
  tball: {
    key: 'tball',
    name: 'T-ball',
    category: 'team',
    formats: [placement()],
    rosterMax: 12,
    age,
    venue: 'field',
    contest: 'Game',
    duration: 45,
    rubric: 'Throwing|Catching|Hitting|Participation',
    standings: { publicVisibility: 'hidden' },
  },
  volleyball: {
    key: 'volleyball',
    name: 'Volleyball',
    es: 'Voleibol',
    category: 'team',
    formats: [sets(3, 25, 15)],
    positions: 'S|OH|MB|OPP|L|DS',
    rosterMax: 12,
    onField: 6,
    age,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serving|Passing|Setting|Attacking|Defending',
    officials: 'First referee|Second referee|Line judge',
    discipline: 'Red card',
    standings: {
      tiebreakers: [
        'head_to_head_points',
        'set_ratio',
        'point_ratio',
        'coin_toss_manual',
      ],
    },
  },
  beach_volleyball: {
    key: 'beach_volleyball',
    name: 'Beach volleyball',
    category: 'team',
    formats: [sets(3, 21, 15)],
    rosterMax: 2,
    onField: 2,
    age,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serving|Passing|Setting|Attacking',
    officials: 'Referee',
  },
  flag_football: {
    key: 'flag_football',
    name: 'Flag football',
    category: 'team',
    formats: [score('Half', 2, true)],
    positions: 'QB|C|WR|RB|DEF',
    rosterMax: 12,
    onField: 7,
    age: grade,
    venue: 'field',
    contest: 'Game',
    rubric: 'Throwing|Catching|Route running|Flag pulling',
    officials: 'Referee|Line judge',
  },
  tackle_football: {
    key: 'tackle_football',
    name: 'Tackle football',
    category: 'team',
    formats: [score('Quarter', 4, false)],
    positions: 'QB|RB|WR|TE|OL|DL|LB|DB|K',
    rosterMax: 40,
    onField: 11,
    age,
    venue: 'field',
    contest: 'Game',
    rubric: 'Technique|Position skill|Game awareness|Conditioning',
    officials: 'Referee|Umpire|Line judge',
    discipline: 'Ejection',
  },
  ice_hockey: {
    key: 'ice_hockey',
    name: 'Ice hockey',
    category: 'team',
    formats: [
      score('Period', 3, false, {
        overtime: { label: t('Overtime', 'Prórroga') },
        shootout: true,
      }),
    ],
    positions: 'C|LW|RW|D|G',
    rosterMax: 20,
    onField: 6,
    age: birthN,
    venue: 'rink',
    contest: 'Game',
    rubric: 'Skating|Puck control|Passing|Positioning|Defending',
    officials: 'Referee|Linesperson',
    discipline: 'Minor penalty|Major penalty|Ejection',
    stats: [stats('penalty_minutes', 'Penalty minutes', 'PIM')],
  },
  roller_hockey: {
    key: 'roller_hockey',
    name: 'Roller hockey',
    category: 'team',
    formats: [score('Half', 2, false)],
    positions: 'F|D|G',
    rosterMax: 14,
    age: birth,
    venue: 'rink',
    contest: 'Game',
    rubric: 'Skating|Puck control|Passing|Positioning',
    officials: 'Referee',
  },
  field_hockey: {
    key: 'field_hockey',
    name: 'Field hockey',
    category: 'team',
    formats: [score('Quarter', 4, true)],
    positions: 'GK|DEF|MID|FWD',
    rosterMax: 18,
    onField: 11,
    age: grade,
    venue: 'field',
    contest: 'Game',
    rubric: 'Stick control|Passing|Defending|Game awareness',
    officials: 'Umpire',
    discipline: 'Green card|Yellow card|Red card',
  },
  lacrosse: {
    key: 'lacrosse',
    name: 'Lacrosse',
    category: 'team',
    formats: [score('Quarter', 4, false)],
    positions: 'A|M|D|G|LSM|FO',
    rosterMax: 25,
    age: birth,
    venue: 'field',
    contest: 'Game',
    rubric: 'Stick skills|Passing|Shooting|Defending',
    officials: 'Referee|Umpire',
    discipline: 'Ejection',
  },
  rugby: {
    key: 'rugby',
    name: 'Rugby',
    category: 'team',
    formats: [score('Half', 2, true)],
    positions:
      'Forward 1|Forward 2|Forward 3|Forward 4|Forward 5|Forward 6|Forward 7|Forward 8|Back 9|Back 10|Back 11|Back 12|Back 13|Back 14|Back 15',
    rosterMax: 26,
    onField: 15,
    age: grade,
    venue: 'field',
    contest: 'Match',
    rubric: 'Passing|Tackling|Running lines|Game awareness',
    officials: 'Referee|Assistant referee',
    discipline: 'Yellow card|Red card',
    standings: {
      points: {
        win: 4,
        overtimeWin: 4,
        tie: 2,
        overtimeLoss: 0,
        loss: 0,
        forfeitWin: 4,
        forfeitLoss: 0,
        forfeitDeduction: 0,
      },
    },
  },
  water_polo: {
    key: 'water_polo',
    name: 'Water polo',
    category: 'team',
    formats: [score('Quarter', 4, false)],
    positions: 'GK|Field',
    rosterMax: 15,
    onField: 7,
    age: birth,
    venue: 'pool',
    contest: 'Game',
    rubric: 'Swimming|Passing|Shooting|Positioning',
    officials: 'Referee',
    stats: [stats('exclusions', 'Exclusions', 'EX')],
  },
  ultimate: {
    key: 'ultimate',
    name: 'Ultimate',
    category: 'team',
    formats: [score('Half', 2, false)],
    positions: 'Handler|Cutter',
    rosterMax: 20,
    onField: 7,
    age: grade,
    venue: 'field',
    contest: 'Game',
    rubric: 'Throwing|Catching|Cutting|Spirit',
    officials: 'Observer',
    stats: [stats('spirit_score', 'Spirit score', 'SP')],
  },
  handball: {
    key: 'handball',
    name: 'Handball',
    category: 'team',
    formats: [score('Half', 2, true)],
    positions: 'GK|LW|LB|CB|RB|RW|P',
    rosterMax: 16,
    onField: 7,
    age: birth,
    venue: 'court',
    contest: 'Match',
    rubric: 'Passing|Shooting|Defending|Movement',
    officials: 'Referee',
  },
  cricket: {
    key: 'cricket',
    name: 'Cricket',
    category: 'team',
    formats: [score('Innings', 2, true)],
    positions: 'Batter|Bowler|All-rounder|WK',
    rosterMax: 15,
    onField: 11,
    age,
    venue: 'field',
    contest: 'Match',
    duration: 180,
    rubric: 'Batting|Bowling|Fielding|Game awareness',
    officials: 'Umpire|Scorer',
  },
  tennis: {
    key: 'tennis',
    name: 'Tennis',
    es: 'Tenis',
    category: 'hybrid',
    formats: [sets(3, 6, 6, { scoringUnit: 'games', tiebreakAt: 6 })],
    positions: 'Singles|Doubles',
    rosterMax: 12,
    age,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serve|Forehand|Backhand|Movement|Match strategy',
    officials: 'Chair umpire|Line judge',
  },
  pickleball: {
    key: 'pickleball',
    name: 'Pickleball',
    category: 'individual',
    formats: [sets(3, 11, 11)],
    positions: 'Singles|Doubles',
    rosterMax: 2,
    age: none,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serve|Dinking|Volley|Court positioning',
    officials: 'Referee',
  },
  badminton: {
    key: 'badminton',
    name: 'Badminton',
    category: 'individual',
    formats: [sets(3, 21, 21, { cap: 30 })],
    positions: 'Singles|Doubles',
    rosterMax: 2,
    age,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serve|Footwork|Clear|Smash',
    officials: 'Umpire|Line judge',
  },
  table_tennis: {
    key: 'table_tennis',
    name: 'Table tennis',
    category: 'individual',
    formats: [sets(5, 11, 11)],
    rosterMax: 2,
    age,
    venue: 'court',
    contest: 'Match',
    rubric: 'Serve|Footwork|Spin|Rally control',
    officials: 'Umpire',
  },
  swimming: {
    key: 'swimming',
    name: 'Swimming',
    es: 'Natación',
    category: 'hybrid',
    formats: [
      timed(
        [
          '25_free',
          '50_free',
          '100_free',
          '200_free',
          '50_back',
          '50_breast',
          '50_fly',
          '100_im',
          '200_im',
          'freestyle_relay',
        ],
        { heats: true, lanes: 8, placePoints: [6, 4, 3, 2, 1] },
      ),
    ],
    positions: 'Free|Back|Breast|Fly|IM',
    rosterMax: 200,
    age,
    venue: 'pool',
    contest: 'Meet',
    coach: 'Instructor',
    rubric: 'Stroke technique|Starts|Turns|Endurance',
    uniforms: 'Cap|Suit',
    officials: 'Starter|Referee|Stroke judge|Timer',
    skillLevels: [
      {
        name: t('Beginner', 'Principiante'),
        skills: [t('Floating', 'Flotación'), t('Kicking', 'Patada')],
      },
      {
        name: t('Intermediate', 'Intermedio'),
        skills: [t('Freestyle', 'Estilo libre'), t('Backstroke', 'Espalda')],
      },
    ],
  },
  diving: {
    key: 'diving',
    name: 'Diving',
    category: 'individual',
    formats: [
      judged(['springboard', 'platform'], 5, {
        panel: {
          judges: 5,
          dropHighLow: true,
          components: [
            { key: 'execution', label: t('Execution'), max: 10 },
            { key: 'dd', label: t('Degree of difficulty'), max: 5 },
          ],
          combine: 'sum',
        },
      }),
    ],
    rosterMax: 30,
    age,
    venue: 'pool',
    contest: 'Meet',
    rubric: 'Approach|Takeoff|Form|Entry',
    uniforms: 'Suit',
    officials: 'Referee|Judge',
  },
  track_field: {
    key: 'track_field',
    name: 'Track and field',
    category: 'hybrid',
    formats: [
      timed(['100m', '200m', '400m', '800m', 'relay_4x100'], {
        heats: true,
        lanes: 8,
        placePoints: [10, 8, 6, 5, 4, 3, 2, 1],
      }),
      measured(['long_jump', 'high_jump', 'shot_put', 'discus'], false, 'm', {
        attempts: 3,
        placePoints: [10, 8, 6, 5, 4, 3, 2, 1],
      }),
    ],
    positions: 'Sprints|Distance|Jumps|Throws',
    rosterMax: 80,
    age,
    venue: 'track',
    contest: 'Meet',
    rubric: 'Technique|Speed|Endurance|Coachability',
    officials: 'Starter|Field judge|Timer',
  },
  cross_country: {
    key: 'cross_country',
    name: 'Cross country',
    category: 'hybrid',
    formats: [timed(['5k', '3k'], { placePoints: [] })],
    rosterMax: 40,
    age: grade,
    venue: 'course',
    contest: 'Meet',
    rubric: 'Pacing|Endurance|Race strategy|Consistency',
    officials: 'Starter|Course marshal|Timer',
  },
  gymnastics: {
    key: 'gymnastics',
    name: 'Gymnastics',
    es: 'Gimnasia',
    category: 'hybrid',
    formats: [
      judged(
        [
          'vault',
          'uneven_bars',
          'balance_beam',
          'floor',
          'pommel_horse',
          'still_rings',
          'parallel_bars',
          'high_bar',
        ],
        4,
        {
          panel: {
            judges: 4,
            dropHighLow: true,
            components: [
              { key: 'difficulty', label: t('Difficulty'), max: 10 },
              { key: 'execution', label: t('Execution'), max: 10 },
              { key: 'penalty', label: t('Penalty'), max: 10 },
            ],
            combine: 'average',
          },
        },
      ),
    ],
    positions: 'VT|UB|BB|FX|PH|SR|PB|HB',
    rosterMax: 30,
    age,
    venue: 'gym',
    contest: 'Meet',
    coach: 'Instructor',
    rubric: 'Form|Strength|Flexibility|Routine execution',
    officials: 'Judge|Meet referee',
    skillLevels: [
      { name: t('Level 1'), skills: [t('Forward roll'), t('Handstand')] },
      { name: t('Level 10'), skills: [t('Advanced routines')] },
      { name: t('Xcel'), skills: [t('Xcel routines')] },
    ],
  },
  cheer: {
    key: 'cheer',
    name: 'Cheer',
    category: 'team',
    formats: [judged(['routine'], 4), placement()],
    positions: 'Flyer|Base|Backspot|Tumbler',
    rosterMax: 36,
    age,
    venue: 'gym',
    contest: 'Competition',
    rubric: 'Tumbling|Stunts|Dance|Synchronization',
    officials: 'Judge',
    discipline: 'Safety violation',
  },
  dance: {
    key: 'dance',
    name: 'Dance',
    es: 'Danza',
    category: 'hybrid',
    formats: [judged(['routine'], 4), placement()],
    rosterMax: 30,
    age: none,
    venue: 'studio',
    contest: 'Competition',
    coach: 'Instructor',
    rubric: 'Technique|Musicality|Expression|Synchronization',
    uniforms: 'Costume|Shoes',
    officials: 'Judge',
    skillLevels: [
      { name: t('Beginner', 'Principiante'), skills: [t('Basic steps')] },
      { name: t('Advanced', 'Avanzado'), skills: [t('Advanced choreography')] },
    ],
  },
  figure_skating: {
    key: 'figure_skating',
    name: 'Figure skating',
    category: 'individual',
    formats: [judged(['short_program', 'free_skate'], 5)],
    rosterMax: 20,
    age,
    venue: 'rink',
    contest: 'Competition',
    rubric: 'Edges|Jumps|Spins|Presentation',
    uniforms: 'Costume|Skates',
    officials: 'Judge|Technical specialist',
    skillLevels: [
      { name: t('Basic'), skills: [t('Forward skating')] },
      { name: t('Advanced'), skills: [t('Jumps')] },
    ],
  },
  wrestling: {
    key: 'wrestling',
    name: 'Wrestling',
    es: 'Lucha',
    category: 'hybrid',
    formats: [bout(methods)],
    positions: 'Weight class',
    rosterMax: 40,
    age: grade,
    venue: 'mat',
    contest: 'Dual',
    rubric: 'Takedowns|Escapes|Top control|Conditioning',
    uniforms: 'Singlet|Headgear',
    officials: 'Referee',
    discipline: 'Unsportsmanlike conduct|Ejection',
  },
  martial_arts: {
    key: 'martial_arts',
    name: 'Martial arts',
    category: 'individual',
    formats: [
      bout(
        [
          ['points', 1],
          ['submission', 1],
        ],
        'Round',
        3,
      ),
      placement(['forms']),
    ],
    rosterMax: 50,
    age: none,
    venue: 'mat',
    contest: 'Tournament',
    coach: 'Instructor',
    rubric: 'Technique|Control|Respect|Forms',
    uniforms: 'Uniform|Belt',
    officials: 'Referee|Judge',
    skillLevels: [
      { name: t('White belt'), skills: [t('Foundations')] },
      { name: t('Black belt'), skills: [t('Advanced techniques')] },
    ],
  },
  judo_bjj: {
    key: 'judo_bjj',
    name: 'Judo / BJJ',
    category: 'individual',
    formats: [
      bout(
        [
          ['ippon', 1],
          ['submission', 1],
          ['points', 1],
        ],
        'Round',
        1,
      ),
    ],
    positions: 'Weight class',
    rosterMax: 50,
    age,
    venue: 'mat',
    contest: 'Bout',
    coach: 'Sensei',
    rubric: 'Throws|Ground control|Defense|Conditioning',
    uniforms: 'Gi|Belt',
    officials: 'Referee',
    skillLevels: [
      { name: t('White belt'), skills: [t('Breakfall')] },
      { name: t('Black belt'), skills: [t('Advanced technique')] },
    ],
  },
  boxing: {
    key: 'boxing',
    name: 'Boxing',
    es: 'Boxeo',
    category: 'individual',
    formats: [
      bout(
        [
          ['decision', 1],
          ['stoppage', 1],
        ],
        'Round',
        3,
      ),
    ],
    positions: 'Weight class',
    rosterMax: 30,
    age,
    venue: 'ring',
    contest: 'Bout',
    rubric: 'Footwork|Defense|Combinations|Conditioning',
    uniforms: 'Trunks|Gloves',
    officials: 'Referee|Judge',
  },
  fencing: {
    key: 'fencing',
    name: 'Fencing',
    es: 'Esgrima',
    category: 'hybrid',
    formats: [bout([['touches', 1]], 'Period', 3)],
    positions: 'Foil|Épée|Sabre',
    rosterMax: 30,
    age: birth,
    venue: 'piste',
    contest: 'Bout',
    rubric: 'Footwork|Blade work|Timing|Tactics',
    uniforms: 'Jacket|Mask|Glove',
    officials: 'Referee',
  },
  golf: {
    key: 'golf',
    name: 'Golf',
    category: 'hybrid',
    formats: [measured(['9_holes', '18_holes'], true, 'strokes')],
    rosterMax: 12,
    age: grade,
    venue: 'course',
    contest: 'Round',
    rubric: 'Driving|Approach|Short game|Putting',
    uniforms: 'Polo|Cap',
    officials: 'Rules official',
  },
  bowling: {
    key: 'bowling',
    name: 'Bowling',
    category: 'hybrid',
    formats: [
      measured(['game_1', 'game_2', 'game_3'], false, 'pins', { attempts: 3 }),
    ],
    rosterMax: 10,
    age,
    venue: 'lanes',
    contest: 'Match',
    rubric: 'Approach|Release|Accuracy|Consistency',
    uniforms: 'Team shirt',
    officials: 'Scorekeeper',
  },
  archery: {
    key: 'archery',
    name: 'Archery',
    es: 'Tiro con arco',
    category: 'individual',
    formats: [measured(['ends'], false, 'points')],
    rosterMax: 20,
    age,
    venue: 'range',
    contest: 'Competition',
    rubric: 'Form|Aim|Release|Consistency',
    uniforms: 'Team shirt',
    officials: 'Judge',
  },
  cycling: {
    key: 'cycling',
    name: 'Cycling',
    es: 'Ciclismo',
    category: 'individual',
    formats: [timed(['road_race', 'time_trial'])],
    rosterMax: 30,
    age,
    venue: 'course',
    contest: 'Race',
    rubric: 'Bike handling|Pacing|Endurance|Race awareness',
    uniforms: 'Jersey|Shorts',
    officials: 'Commissaire',
  },
  skiing_snowboard: {
    key: 'skiing_snowboard',
    name: 'Skiing / snowboard',
    category: 'individual',
    formats: [timed(['slalom', 'giant_slalom', 'snowboard_cross'])],
    positions: 'Ski|Snowboard',
    rosterMax: 30,
    age: birth,
    venue: 'slope',
    contest: 'Race',
    rubric: 'Edge control|Turns|Balance|Race line',
    uniforms: 'Bib|Helmet',
    officials: 'Starter|Gate judge',
  },
  rowing: {
    key: 'rowing',
    name: 'Rowing',
    es: 'Remo',
    category: 'hybrid',
    formats: [timed(['single', 'double', 'four', 'eight'])],
    positions: 'Seat 1|Seat 2|Seat 3|Seat 4|Seat 5|Seat 6|Seat 7|Seat 8|Cox',
    rosterMax: 30,
    age,
    venue: 'water',
    contest: 'Regatta',
    rubric: 'Technique|Timing|Power|Teamwork',
    uniforms: 'Uni|Cap',
    officials: 'Referee|Starter',
  },
  esports: {
    key: 'esports',
    name: 'Esports',
    category: 'team',
    formats: [sets(3, 1, 1, { winBy: 1 })],
    positions: 'Role 1|Role 2|Role 3|Role 4|Role 5',
    rosterMax: 10,
    age: grade,
    venue: 'digital',
    contest: 'Match',
    rubric: 'Strategy|Communication|Mechanics|Teamwork',
    uniforms: 'Jersey',
    officials: 'Match admin',
  },
  chess: {
    key: 'chess',
    name: 'Chess',
    es: 'Ajedrez',
    category: 'individual',
    formats: [
      bout(
        [
          ['win', 1],
          ['draw', 0.5],
          ['loss', 0],
        ],
        'Round',
        1,
      ),
    ],
    positions: 'Board',
    rosterMax: 10,
    age: grade,
    venue: 'room',
    contest: 'Match',
    rubric: 'Opening|Tactics|Endgame|Time management',
    uniforms: 'Team shirt',
    officials: 'Arbiter',
  },
  climbing: {
    key: 'climbing',
    name: 'Climbing',
    es: 'Escalada',
    category: 'individual',
    formats: [measured(['bouldering', 'lead', 'speed'], false, 'points')],
    rosterMax: 30,
    age: birth,
    venue: 'wall',
    contest: 'Competition',
    rubric: 'Technique|Route reading|Strength|Problem solving',
    uniforms: 'Team shirt',
    officials: 'Judge',
  },
  general_activity: {
    key: 'general_activity',
    name: 'General activity',
    es: 'Actividad general',
    category: 'individual',
    formats: [placement()],
    rosterMax: 100,
    age: none,
    venue: 'room',
    contest: 'Activity',
    coach: 'Instructor',
    rubric: 'Participation|Effort|Progress|Teamwork',
    uniforms: 'Team shirt',
  },
};

export function getTemplateSeed(key: string): TemplateSeed {
  const seed = templateSeeds[key];
  if (!seed) throw new RangeError(`Unknown sport template: ${key}`);
  return seed;
}
