import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowDown, Plus, Minus, Menu, X, Check, CalendarDays, Users, ClipboardList } from 'lucide-react';
import './landing.css';
const tours = [
 {name:'Overview', title:'A clear view. A better starting point.', text:'See your programs, registrations, and outstanding balances in one workspace.', path:'/'},
 {name:'Registration', title:'From interested to on the roster.', text:'Manage program enrollment, custom forms, waivers, and registration status.', path:'/registrations'},
 {name:'Scheduling', title:'Give every team a place to be.', text:'Organize games and practices across programs, teams, and locations.', path:'/schedule'},
 {name:'Payments', title:'Know what’s paid. See what’s next.', text:'Review invoices, track balances, and manage payment plans in context.', path:'/invoices'},
];
const faqs=[['Who is Athlentry for?','Athlentry is built for the people running sports organizations: administrators managing programs, coaches working with teams, and families participating in the season.'],['What can I manage in Athlentry?','Programs, registrations, rosters, schedules, invoices, payment plans, messaging, and your organization’s public website. Explore the product tour to see how the pieces connect.'],['Can families access their own information?','Yes. Organization websites include member accounts where families can access registration and account information. Staff access is managed separately through roles and permissions.'],['How can I explore the platform?','Use Open platform to reach the sign-in screen or your existing workspace. The tour on this page is available without an account and uses illustrative demo data.']];
export function Landing(){
 const [menu,setMenu]=useState(false),[tour,setTour]=useState(0),[faq,setFaq]=useState<number|null>(null); const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const old=document.title;document.title='Athlentry — Your next season starts here';const media=matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const update=()=>{frame=0;root.current?.style.setProperty('--travel',`${Math.min(window.scrollY*.18,150)}px`)};const scroll=()=>{if(!media.matches&&!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',scroll,{passive:true});return()=>{document.title=old;window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame)}},[]);
 return <div className="al" ref={root}>
 <a className="al-skip" href="#main">Skip to content</a>
 <header className="al-nav"><Link className="al-logo" to="/welcome" aria-label="Athlentry home"><span className="al-symbol">A</span>athlentry</Link><nav aria-label="Main navigation" className={menu?'is-open':''}><a href="#platform" onClick={()=>setMenu(false)}>The platform</a><a href="#people" onClick={()=>setMenu(false)}>Built for you</a><a href="#questions" onClick={()=>setMenu(false)}>Questions</a><Link to="/" className="al-nav-cta">Open platform <ArrowUpRight size={17}/></Link></nav><button className="al-menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main">
 <section className="al-hero"><div className="al-hero-top"><p className="al-label"><span/> SPORTS MANAGEMENT. MOVING FORWARD.</p><h1>Your next season<br/>starts <em>here.</em><span className="al-hero-arrow" aria-hidden="true">↗</span></h1><div className="al-intro"><p>Less time behind the scenes.<br/>More room for the game.<br/><span>Bring your sports organization together with Athlentry.</span></p><a className="al-button" href="#platform">Explore the platform <ArrowDown size={18}/></a></div></div><div className="al-photo"><div className="al-photo-art" aria-hidden="true"><span/><span/><span/><span/></div><div className="al-photo-caption"><span>FOR EVERYTHING THAT MAKES<br/>GAME DAY POSSIBLE.</span><span>THE NEXT CHAPTER<br/>OF SPORTS MANAGEMENT ↗</span></div></div></section>
 <div className="al-band" aria-label="Platform capabilities"><span>Registrations</span><Plus/><span>Teams</span><Plus/><span>Schedules</span><Plus/><span>Payments</span><Plus/><span>One home.</span></div>
 <section className="al-platform al-section" id="platform"><div className="al-section-heading"><p className="al-label">MEET YOUR NEW HOME BASE</p><h2>Big picture.<br/><span>Every little detail.</span></h2><p>A season has a lot of moving parts. Give them a place to work together.</p></div><div className="al-tour-tabs" role="tablist" aria-label="Explore platform features">{tours.map((t,i)=><button key={t.name} role="tab" id={`tour-tab-${i}`} aria-controls="tour-panel" aria-selected={tour===i} tabIndex={tour===i?0:-1} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;setTour(next);document.getElementById(`tour-tab-${next}`)?.focus()}}} onClick={()=>setTour(i)}>{t.name}<ArrowUpRight size={16}/></button>)}</div><div id="tour-panel" role="tabpanel" aria-labelledby={`tour-tab-${tour}`} className="al-tour-panel"><div className="al-tour-copy"><h3>{tours[tour].title}</h3><p>{tours[tour].text}</p><Link to={tours[tour].path}>Open {tours[tour].name.toLowerCase()} <ArrowUpRight size={17}/></Link></div><div className="al-screen"><div className="al-screen-bar"><span><i/><i/><i/></span><span>Athlentry / {tours[tour].name}</span><span>Demo workspace</span></div><img src={`/landing/${['dashboard','registrations','schedule','invoices'][tour]}.png`} alt={`Athlentry ${tours[tour].name.toLowerCase()} screen with fictional demonstration data`} loading="lazy"/></div></div></section>
 <section className="al-manifesto"><span aria-hidden="true" className="al-track-line"/><div><p>Behind every great season,<br/>there’s someone making it happen.</p><h2>This one’s<br/>for <em>you.</em></h2><a href="#people" aria-label="See who Athlentry is built for"><ArrowDown/></a></div></section>
 <section className="al-people al-section" id="people"><h2>One organization.<br/><span>Everyone connected.</span></h2><div className="al-people-grid"><article><ClipboardList/><span>01 / ADMINISTRATORS</span><h3>Run the whole season.</h3><p>From the first registration to the final invoice, keep your programs and people organized.</p><ul><li><Check/>Program and registration management</li><li><Check/>Invoices and payment plans</li><li><Check/>Reports and staff permissions</li></ul></article><article><Users/><span>02 / COACHES</span><h3>Stay close to your team.</h3><p>Keep rosters, events, and attendance together so the next practice starts with everyone informed.</p><ul><li><Check/>Team rosters</li><li><Check/>Games and practice schedules</li><li><Check/>Attendance tracking</li></ul></article><article><CalendarDays/><span>03 / FAMILIES</span><h3>Be part of the season.</h3><p>Find programs, register participants, and access member information through your organization’s website.</p><ul><li><Check/>Online program registration</li><li><Check/>Member accounts</li><li><Check/>Schedules and account information</li></ul></article></div></section>
 <section className="al-faq al-section" id="questions"><h2>A few things<br/>worth knowing.</h2><div>{faqs.map(([q,a],i)=><article key={q}><h3><button aria-expanded={faq===i} aria-controls={`faq-${i}`} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus/>:<Plus/>}</button></h3><div id={`faq-${i}`} hidden={faq!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="al-close"><p>YOUR PEOPLE. YOUR PROGRAMS. YOUR NEXT CHAPTER.</p><h2>Make room<br/>for more <em>sports.</em></h2><Link className="al-button" to="/">Open Athlentry <ArrowUpRight/></Link><a href="#platform">Take another look at the platform</a><span className="al-close-mark" aria-hidden="true">A</span></section>
 </main><footer className="al-footer"><Link to="/welcome" className="al-logo">athlentry</Link><span>Sports management. Moving forward.</span><span>© {new Date().getFullYear()} Athlentry</span><a href="#main">Back to top ↑</a></footer>
 </div>
}
